# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  branches:
    include:
    - azure-pipeline
    exclude:
    - master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# Node.js tool installer
# Finds or downloads and caches the specified version spec of Node.js and adds it to the PATH
- task: NodeTool@0
  inputs:
    versionSpec: '8.11.1'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/ProjectReportJob.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.artifactStagingDirectory)/App_Data/jobs/continuous -r win-x64 --self-contained false'
    zipAfterPublish: false
  displayName: 'Publish web job'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    modifyOutputPath: false
    arguments: '--configuration $(buildConfiguration) --output $(Build.artifactStagingDirectory)'
    zipAfterPublish: true
  displayName: 'Publish web project'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
     **\$(BuildConfiguration)\*test*.dll
     **\$(BuildConfiguration)\**\*test*.dll
     !**\*Microsoft.VisualStudio.TestPlatform*
     !**\obj\**
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

#New Task Added to publish build artifacts so release pipe lines can work
- task: PublishBuildArtifacts@1
